@echo off
echo Starting Prompt Gallery Development Servers...
echo.
echo Starting Backend API Server...
start cmd /k "cd %~dp0server && npm start"
echo.
echo Starting Frontend Vue.js Server...
start cmd /k "cd %~dp0 && npm run dev"
echo.
echo Both servers are starting. Please wait a moment...
echo Frontend: http://localhost:5173
echo Backend: http://localhost:5000